### ISSUE TITLE
Violation of MIT license.

### ISSUE THREAD

**Issue by ethanrjones97** [garretyoder/GifMatrix#4]
Currently this repository is violating the MIT license of it's origin project because it lacks the MIT license file and copyright notice. 

https://github.com/pixelmatix/AnimatedGIFs/blob/master/LICENSE.txt

**Comment by per1234** [comment]
@garretyoder why did you close this? I don't understand why you're so resistant to respecting the license of the code you used.

**Comment by garretyoder** [comment]
It's a unimportant thing for me. This is a project that I wrote for a friend a long time ago and haven't touched or cared about since. I closed this when I did a issue cleanup of all my projects.

To me it doesn't matter because nobody is really using this. It's old and outdated with new versions of the shield. If this is causing a itch that you can't scratch then feel free to add a license text file in a PR and I'll merge it, it's simply unimportant to me.

**Comment by per1234** [comment]
>It's a unimportant thing for me.

Clearly it is important to others since you have had three pull requests to add a license, one issue report, and four reactions to that issue report. Of course that's only the visible signs, the tip of the iceberg if you will. Who knows how many others have noticed the issue but then seen that attempts were already made to get the issue resolved?

>To me it doesn't matter because nobody is really using this.

Well, since there is no license it's all rights reserved so maybe that has something to do with it? Also, there seems to have been a fair amount of activity (some within the last year) for a project that nobody is really using.

>feel free to add a license text file in a PR and I'll merge it

What about the three previous PRs that tried to do just that, but were ignored?

- https://github.com/garretyoder/GifMatrix/pull/1/files
- https://github.com/garretyoder/GifMatrix/pull/2/files
- https://github.com/garretyoder/GifMatrix/pull/3/files
